name: Python and Node.js CI

on:
    - pull_request
    - push

jobs:
    ci:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: [3.7, 3.8, 3.9]
                node-version: [12, 14, 16]
        steps:
            - uses: actions/checkout@main
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@main
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Display Python version
              run: python -c "import sys; print(sys.version)"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip wheel setuptools
                  pip install -r requirements.txt
            - name: Random query
              run: python getRating.py "Hello World!"
            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@main
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: |
                  npm i -g npm
                  npm ci
            - name: Lint
              run: npm run lint
              env:
                  CI: true
            - name: Start server
              run: nohup node index.js >> server.log 2>&1 &
            - name: Run tests
              run: npm test
            - name: Print logs
              run: cat server.log
