name: Lint with flake8

on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Set up Python 3.9
              uses: actions/setup-python@main
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip wheel setuptools flake8
            - name: Lint with flake8
              run: flake8 --filename=getRating.py --count --show-source --statistics --ignore=E501 --exit-zero
