name: Node.js CI

on:
    - pull_request
    - push

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: ["12", "14", "16"]
        steps:
            - uses: actions/checkout@main
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@main
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: |
                  sudo npm i -g npm
                  npm ci
            - name: Lint
              run: npm run lint
              env:
                  CI: true
            - name: Run tests
              run: npm test
