name: Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        echo -e "\n\n\t\tInstalling / Upgrading pip\n\n"
        python -m pip install --upgrade pip
        echo -e "\n\n\t\tInstalling / Upgrading virtualenv\n\n"
        pip install virtualenv
        echo -e "\n\n\t\tCreating virtual environment \"virtualenv\"\n\n"
        virtualenv virtualenv
        echo -e "\n\n\t\tActivating virtual environment \"virtualenv\"\n\n"
        . virtualenv/Scripts/activate
        echo -e "\n\n\t\tInstalling dependencies in virtual environment \"virtualenv\"\n\n"
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --filename=getRating.py --count --show-source --statistics --ignore=E501 --exit-zero
    - name: Random query
      run: |
        python getRating.py "Hello World!"
