name: Python

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3 latest
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        echo -e "\n\n\t\tInstalling / Upgrading pip\n\n"
        python -m pip install --upgrade pip
        echo -e "\n\n\t\tInstalling dependencies\n\n"
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --filename=getRating.py --count --show-source --statistics --ignore=E501 --exit-zero
    - name: Random query
      run: |
        python getRating.py "Hello World!"
